/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Pharmacy;

import UserInterface.PatientManagementRole.*;
import Business.Ecosystem;
import Business.Enterprise.DrugCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.Pharmacy.Pharmacy;
import Business.Pharmacy.PharmacyDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.HospitalManagementWorkArea.ManageUserAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krithika
 */
public class ManagePharmacy extends javax.swing.JPanel {
JPanel userProcessContainer;
private PharmacyDirectory pharmacyDirectory;
private UserAccount userAccount;

private Enterprise enterprise;
    private Organization organization; 
    Ecosystem business;
    Pharmacy p;/**
     * Creates new form ManagePatients
     */
    public ManagePharmacy(JPanel upc,Pharmacy p, PharmacyDirectory pharmacyDirectory,
            UserAccount userAccount,Organization organization,
            Enterprise enterprise,Ecosystem business) {
        initComponents();
        this.pharmacyDirectory=pharmacyDirectory;
        this.enterprise=enterprise;
        this.userProcessContainer=upc;
        this.userAccount=userAccount;
        this.organization=organization;
        this.business=business;
        this.p=p;
        refresh();
    }
public void refresh() {
        DefaultTableModel dtm = (DefaultTableModel) pharmacyCompanyJTable.getModel();
        //cleaning the table
        dtm.setRowCount(0);
        //populating the table
        
        for (Pharmacy p : ((DrugCompanyEnterprise)enterprise).
                getPharmacyDirectory().getPharmacyDirectory())
        {
            Object row[] = new Object[4];
            row[0] = p;
            row[1] = p.getCity();
            row[2] = p.getState();
            row[3] = p.getContactNumber();
            dtm.addRow(row);
        }

    }

        
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pharmacyCompanyJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 102, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackJButton.setText("<< Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });
        add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 223, -1, -1));

        pharmacyCompanyJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "City", "State", "ContactNo"
            }
        ));
        jScrollPane1.setViewportView(pharmacyCompanyJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, 426, 91));
    }// </editor-fold>//GEN-END:initComponents

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);          // TODO add your handling code here:
    }//GEN-LAST:event_BackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pharmacyCompanyJTable;
    // End of variables declaration//GEN-END:variables
}
