/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Pharmacy;

import UserInterface.PatientManagementRole.*;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Message.Message;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.Pharmacy.Pharmacy;
import Business.Pharmacy.PharmacyDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.HospitalManagementWorkArea.AddDoctor;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Krithika
 */
public class PharmacyWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmacyDirectory pharmacyDirectory;
    Pharmacy p;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    Ecosystem business;

    /**
     * Creates new form PatientWorkArea
     */
    public PharmacyWorkArea(JPanel upc, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = upc;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.account = account;
        Message message = Message.getInstance();
        jTextField1.setText(message.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddPharmacy = new javax.swing.JButton();
        ManagePharmacy = new javax.swing.JButton();
        ManagePharmacyAccount = new javax.swing.JButton();
        PatientNotFOund = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Pharmacy Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 26, -1, -1));

        AddPharmacy.setText("Add Pharmacy");
        AddPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPharmacyActionPerformed(evt);
            }
        });
        add(AddPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 101, 147, 21));

        ManagePharmacy.setText("View Pharmacy");
        ManagePharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePharmacyActionPerformed(evt);
            }
        });
        add(ManagePharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 134, -1, -1));

        ManagePharmacyAccount.setText("Manage Pharmacy Account");
        ManagePharmacyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePharmacyAccountActionPerformed(evt);
            }
        });
        add(ManagePharmacyAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 169, -1, -1));
        add(PatientNotFOund, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 101, 180, 20));

        jLabel6.setText("Message");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 286, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 269, 150, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void AddPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPharmacyActionPerformed
        AddPharmacy AddPatientJPanel = new AddPharmacy(userProcessContainer, p,
                pharmacyDirectory, account, organization, enterprise, business);
        userProcessContainer.add("AddPatient", AddPatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);           // TODO add your handling code here:
    }//GEN-LAST:event_AddPharmacyActionPerformed

    private void ManagePharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePharmacyActionPerformed
        ManagePharmacy ManagePharmacyJPanel = new ManagePharmacy(userProcessContainer,
                p, pharmacyDirectory, account, organization, enterprise, business);
        userProcessContainer.add("ManagePatient", ManagePharmacyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagePharmacyActionPerformed

    private void ManagePharmacyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePharmacyAccountActionPerformed
        ManageUserAccount ManageUSerAccountJPanel = new ManageUserAccount(
                userProcessContainer, p, pharmacyDirectory, account, 
                organization, enterprise, business);
        userProcessContainer.add("ManageUserAccount", ManageUSerAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

// TODO add your handling code here:
    }//GEN-LAST:event_ManagePharmacyAccountActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPharmacy;
    private javax.swing.JButton ManagePharmacy;
    private javax.swing.JButton ManagePharmacyAccount;
    private javax.swing.JLabel PatientNotFOund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
