/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugWorkArea;

import Business.Drug.DrugCompany;
import Business.Drug.DrugCompanyDirectory;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.DrugCompany.ManageDrugs;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author krithika
 */
public class HomePageJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Enterprise enterprise;
    UserAccount account;
    Organization organization;
    Ecosystem business;
    
    /**
     * Creates new form HomePageJPanel
     */
    public HomePageJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.container = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drugName = new javax.swing.JTextField();
        drugDescription = new javax.swing.JTextField();
        addDrug = new javax.swing.JButton();
        feedBack = new javax.swing.JButton();
        requests = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Drug Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 53, -1, -1));

        jLabel2.setText("Description");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 99, -1, -1));

        drugName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugNameActionPerformed(evt);
            }
        });
        add(drugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 47, 117, -1));
        add(drugDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 93, 117, -1));

        addDrug.setText("Add Drug");
        addDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugActionPerformed(evt);
            }
        });
        add(addDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        feedBack.setText("Feedback");
        feedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedBackActionPerformed(evt);
            }
        });
        add(feedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 110, -1));

        requests.setText("View Requests");
        requests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsActionPerformed(evt);
            }
        });
        add(requests, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Drug Company Home Page");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/medicine.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 46, 380, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void drugNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugNameActionPerformed

    private void addDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugActionPerformed
        // TODO add your handling code here:
        String drugNameVal = drugName.getText();
        String drugDescriptionVal = drugDescription.getText();
        System.out.print(account.getCompany());
        DrugCompany dc = (DrugCompany)account.getCompany();
        dc.getMedicines().addMedicineList(new Medicine(drugNameVal, drugDescriptionVal));
        JOptionPane.showMessageDialog(null, "Drug added");
        
    }//GEN-LAST:event_addDrugActionPerformed

    private void feedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedBackActionPerformed
        // TODO add your handling code here:
       ViewFeedBack viewFeedBack = new ViewFeedBack(container, account);
       container.add("ManageDoctor", viewFeedBack);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);   
    }//GEN-LAST:event_feedBackActionPerformed

    private void requestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsActionPerformed
        // TODO add your handling code here:
       PharmaRequests pharmaRequests = new PharmaRequests(container, account, enterprise);
       container.add("ManageDoctor", pharmaRequests);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);  
    }//GEN-LAST:event_requestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrug;
    private javax.swing.JTextField drugDescription;
    private javax.swing.JTextField drugName;
    private javax.swing.JButton feedBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton requests;
    // End of variables declaration//GEN-END:variables
}
