/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugWorkArea;

import Business.Drug.DrugCompany;
import Business.Encounter.Encounter;
import Business.Encounter.EncounterHistory;
import Business.Enterprise.Enterprise;
import Business.Medicine.Feedback;
import Business.Medicine.Medicine;
import Business.Medicine.MedicineInventroy;
import Business.Patient.PrescriptionItem;
import Business.Pharmacy.Pharmacy;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicineInventoryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vyaas
 */
public class PharmaRequests extends javax.swing.JPanel {

    /**
     * Creates new form PharmaRequests
     */
    JPanel upc;
    UserAccount account;
    Enterprise enterprise;
    public PharmaRequests(JPanel upc, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.upc=upc;
        this.account=account;
        this.enterprise = enterprise;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //MedicineInventoryWorkRequest miwr= (MedicineInventoryWorkRequest)account.getWorkQueue().getWorkRequestList();
        model.setRowCount(0);
        for (WorkRequest wr: enterprise.getWorkQueue().getWorkRequestList()){
            if(wr instanceof MedicineInventoryWorkRequest){
            if(wr.getCompanyReceiver()==account.getCompany()){
            MedicineInventoryWorkRequest miwr = (MedicineInventoryWorkRequest) wr;
            Object[] row = new Object[4];
            row[0] = miwr;
            row[1] = miwr.getMedicinesInventroy().getMedicine();
            row[2] = miwr.getMedicinesInventroy().getQuantity();
            row[3] = miwr.getStatus();
            model.addRow(row);
            }
        }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pharmacy", "Drug", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 375, 104));

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Pharmacy Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a drug");
            return;
        }
        MedicineInventoryWorkRequest miwr = (MedicineInventoryWorkRequest) jTable1.getValueAt(selectedRow, 0);
        if(miwr.getStatus().equals("Requested")){
        Pharmacy pharmacy = (Pharmacy)miwr.getSender().getCompany();
        boolean medicinePresent=false;
        for (MedicineInventroy medicine: pharmacy.getMedicines().getMedicinesList()){
            if(medicine.getMedicine()==miwr.getMedicinesInventroy().getMedicine()){
                medicinePresent=true;
                medicine.setQuantity(medicine.getQuantity()+miwr.getMedicinesInventroy().getQuantity());
            }
        }
        if(!medicinePresent){
            pharmacy.getMedicines().getMedicinesList().add
        (new MedicineInventroy((DrugCompany)account.getCompany(), 
                miwr.getMedicinesInventroy().getMedicine(), miwr.getMedicinesInventroy().getQuantity()));
            JOptionPane.showMessageDialog(null, "Drug sent to pharmacy");
        }
        miwr.setStatus("Processed");
        }else{
            JOptionPane.showMessageDialog(null, "Already Processed");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
