/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DrugCompany;

import UserInterface.HospitalManagementWorkArea.*;
import Business.Doctor.Doctor;
import Business.Doctor.DoctorDirectory;
import Business.Drug.DrugCompany;
import Business.Drug.DrugCompanyDirectory;
import Business.Ecosystem;
import Business.Enterprise.DrugCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Krithika
 */
public class AddDrugCompany extends javax.swing.JPanel {
JPanel userProcessContainer;
private DrugCompanyDirectory drugDirectory;
private DrugCompany d;
UserAccount account;
Organization organization;
Enterprise enterprise;
Ecosystem business;
    /**
     * Creates new form AddDoctor
     */
    public AddDrugCompany(JPanel upc,DrugCompanyDirectory dd,DrugCompany d,UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer=upc;
        this.drugDirectory=dd;
        this.d=d;
        this.organization=organization;
        this.enterprise=enterprise;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        addDrugCompany = new javax.swing.JButton();
        BackJButton = new javax.swing.JButton();
        contact = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 74, -1, -1));

        jLabel1.setText("Drug Company Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 28, -1, -1));
        add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 154, 76, -1));

        jLabel6.setText("Contact Number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 200, -1, -1));

        jLabel4.setText("State");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 160, -1, -1));

        jLabel3.setText("City");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 114, -1, -1));
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 108, 76, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 62, 76, -1));

        addDrugCompany.setText("Add Company");
        addDrugCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugCompanyActionPerformed(evt);
            }
        });
        add(addDrugCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        BackJButton.setText("<< Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });
        add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 194, 76, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void addDrugCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugCompanyActionPerformed
     try {
            String nameVal = name.getText();
            String cityVal = city.getText();
            String stateVal = state.getText();
            int contactNo = Integer.parseInt(contact.getText());
            DrugCompany drug = ((DrugCompanyEnterprise)enterprise).getDrugDirectory().addDrug();
            drug.setName(nameVal);
            drug.setCity(cityVal);
            drug.setState(stateVal);
            drug.setContactNumber(contactNo);  
            JOptionPane.showMessageDialog(null, "DrugCompany added");
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Invalid entry", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addDrugCompanyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JButton addDrugCompany;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField state;
    // End of variables declaration//GEN-END:variables
}
