/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientManagementRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Krithika
 */
public class AddPatient extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PatientDirectory patientDirectory;
    Patient p;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    Ecosystem business;

    /**
     * Creates new form AddPatient
     */
    public AddPatient(JPanel upc, Patient p, PatientDirectory pd, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = upc;
        this.patientDirectory = pd;
        this.p = p;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        AddPatientJPanel = new javax.swing.JButton();
        BackJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 26, -1, -1));

        jLabel2.setText("FirstName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 74, -1, -1));

        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 114, -1, -1));

        jLabel4.setText("Age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 160, -1, -1));

        jLabel5.setText("SSN");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 206, -1, -1));

        jLabel6.setText("Contact Number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 252, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 62, 76, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 108, 76, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 154, 76, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 200, 76, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 246, 76, -1));

        AddPatientJPanel.setText("Add Patient");
        AddPatientJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientJPanelActionPerformed(evt);
            }
        });
        add(AddPatientJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        BackJButton.setText("<< Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });
        add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 292, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/docc.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 510, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void AddPatientJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientJPanelActionPerformed
        try {
            String firstName = jTextField1.getText();
            String lastName = jTextField2.getText();
            int age = Integer.parseInt(jTextField3.getText());
            String ssn = jTextField4.getText();
            int contactNo = Integer.parseInt(jTextField5.getText());

            Patient p = ((HospitalEnterprise) enterprise).getPatientDirectory().addPatient(firstName, ssn);
            if(p==null){
               JOptionPane.showMessageDialog(null, "Name and SSN has to be unique."); 
            }else{
            p.setFirstName(firstName);
            p.setLastName(lastName);
            p.setAge(age);
            p.setSsn(ssn);
            p.setContactNumber(contactNo);
            JOptionPane.showMessageDialog(null, "Patient added");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid entry", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPatientJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientJPanel;
    private javax.swing.JButton BackJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
