/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientManagementRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.HospitalManagementWorkArea.ManageUserAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krithika
 */
public class ManagePatients extends javax.swing.JPanel {
JPanel userProcessContainer;
private PatientDirectory patientDirectory;
private UserAccount userAccount;

private Enterprise enterprise;
    private Organization organization; 
    Ecosystem business;
    Patient p;/**
     * Creates new form ManagePatients
     */
    public ManagePatients(JPanel upc,Patient p,PatientDirectory patientDirectory,UserAccount userAccount,Organization organization,Enterprise enterprise,Ecosystem business) {
        initComponents();
        this.patientDirectory=patientDirectory;
        this.enterprise=enterprise;
        this.userProcessContainer=upc;
        this.userAccount=userAccount;
        this.organization=organization;
        this.business=business;
        this.p=p;
        refresh();
    }
public void refresh() {
        DefaultTableModel dtm = (DefaultTableModel) patientsJTable.getModel();
        //cleaning the table
        dtm.setRowCount(0);
        //populating the table
        
        for (Patient pds : ((HospitalEnterprise)enterprise).getPatientDirectory().getPatientDirectory())
        {
            Object row[] = new Object[5];
            row[0] = pds;
            row[1] = pds.getLastName();
            row[2] = pds.getAge();
            row[3] = pds.getSsn();
            row[4] = pds.getContactNumber();
            dtm.addRow(row);
        }

    }

        
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        patientsJTable = new javax.swing.JTable();
        BackJButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FirstName", "LastName", "Age", "SSN", "ContactNo"
            }
        ));
        jScrollPane1.setViewportView(patientsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 520, 110));

        BackJButton.setText("<< Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });
        add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jButton3.setText("Add Encounter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);          // TODO add your handling code here:
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = patientsJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Patient p = (Patient) patientsJTable.getValueAt(selectedRow, 0);
        AddEncounterJPanel addEncounterJPanel = new AddEncounterJPanel(userProcessContainer, p);
       userProcessContainer.add("AddEncounter", addEncounterJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientsJTable;
    // End of variables declaration//GEN-END:variables
}
