/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.HospitalManagementWorkArea;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorDirectory;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Message.Message;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Krithika
 */
public class DoctorWorkArea extends javax.swing.JPanel {
private JPanel upc;
DoctorDirectory dd;
Doctor d;
UserAccount account;
Organization organization;
Enterprise enterprise;
Ecosystem business;
    /**
     * Creates new form DoctorWorkArea
     */
    public DoctorWorkArea(JPanel userProcessContainer,UserAccount account,Organization organization,Enterprise enterprise,Ecosystem business) {
        initComponents();
        this.upc=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.business=business;
        HospitalEnterprise he =(HospitalEnterprise)enterprise;
        dd=he.getDoctorDirectory();
        Message message = Message.getInstance();
        jTextField1.setText(message.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ManageUserAccount = new javax.swing.JButton();
        PatientNotFOund = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Doctor Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 25, -1, -1));

        jButton1.setText("Add Doctor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 147, 139, -1));

        jButton2.setText("View Doctor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 222, -1, -1));

        ManageUserAccount.setText("Manage UserAccount");
        ManageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserAccountActionPerformed(evt);
            }
        });
        add(ManageUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 307, -1, -1));
        add(PatientNotFOund, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 262, 180, 20));

        jLabel6.setText("Message");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 629, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 612, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/male-doctor.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 6, 602, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    AddDoctor AddDoctorJPanel = new AddDoctor(upc,dd,d,account,organization,enterprise,business);
       upc.add("AddDoctor", AddDoctorJPanel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
ManageDoctors ManageDoctorsJPanel = new ManageDoctors(dd,d,upc,account,enterprise,organization,business);
       upc.add("ManageDoctor", ManageDoctorsJPanel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);          
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ManageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserAccountActionPerformed
      ManageUserAccountJPanel ManageUserAccountJPanel = new ManageUserAccountJPanel(dd,d,upc,account,enterprise,organization,business);
       upc.add("ManageUserAccount", ManageUserAccountJPanel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);   
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageUserAccountActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageUserAccount;
    private javax.swing.JLabel PatientNotFOund;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
