/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.HospitalManagementWorkArea;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorDirectory;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krithika
 */
public class ManageDoctors extends javax.swing.JPanel {
JPanel userProcessContainer;
private DoctorDirectory doctorDirectory;
private UserAccount userAccount;
private Enterprise enterprise;
    private Organization organization;   
    private Doctor d;
    private Ecosystem business;
    private PersonDirectory personlist;
    private Person p;/**

    /**
     * Creates new form ManageDoctors
  E   */
    public ManageDoctors(DoctorDirectory doctorDirectory,Doctor d,JPanel upc,UserAccount userAccount,Enterprise enterprise,Organization organization,Ecosystem business) {
        initComponents();
        this.userProcessContainer=upc;
        this.userAccount=userAccount;
        this.doctorDirectory=doctorDirectory;
        this.enterprise=enterprise;
        this.organization=organization;
        this.business=business;
        this.doctorDirectory=doctorDirectory;
        this.d=d;
        refresh();
    }
    public void refresh(){
     DefaultTableModel dtm = (DefaultTableModel) doctorsJTable.getModel();
        //cleaning the table
        dtm.setRowCount(0);
        //populating the table
        
        for (Doctor d : ((HospitalEnterprise)enterprise).getDoctorDirectory().getDoctorDirectory())
        
        
        {
            Object row[] = new Object[6];
            row[0] = d;
            row[1] = d.getLastName();
            row[2] = d.getAge();
            row[3] = d.getSsn();
            row[4] = d.getContactNumber();
            row[5]=d.getHospitalName();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorsJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackJButton.setText("<< Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });
        add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 217, -1, -1));

        doctorsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FirstName", "LastName", "Age", "SSN", "ContactNo"
            }
        ));
        jScrollPane1.setViewportView(doctorsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 363, 91));
    }// </editor-fold>//GEN-END:initComponents

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);          // TODO add your handling code here:
    }//GEN-LAST:event_BackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JTable doctorsJTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
