/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientWorkArea;

import Business.Drug.DrugCompany;
import Business.Encounter.Encounter;
import Business.Medicine.Feedback;
import Business.Network.Network;
import Business.Patient.Patient;
import Business.Patient.Prescription;
import Business.Patient.PrescriptionItem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krithika
 */
public class PrescriptionJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Prescription prescription;
    Network network;
    Patient patient;
    /**
     * Creates new form PrescriptionJPanel
     */
    public PrescriptionJPanel(JPanel userProcessContainer, Patient patient, Prescription prescription, Network network) {
        initComponents();
        this.patient = patient;
        this.network = network;
        this.prescription = prescription;
        this.userProcessContainer = userProcessContainer;
        populateTable();
    }
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
        model.setRowCount(0);
        for (PrescriptionItem prescriptionItem : prescription.getPi()){
                Object[] row = new Object[3];
                row[0] = prescriptionItem;
                row[1] = prescriptionItem.getDrugCompany();
                row[2] = prescriptionItem.getQuantity();
                model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        complainJButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Company", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 65, 375, 92));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 246, -1, -1));

        complainJButton.setText("Post");
        complainJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainJButtonActionPerformed(evt);
            }
        });
        add(complainJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 183, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 169, 167, 54));

        jLabel1.setText("Feedback");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 177, -1, -1));

        jButton2.setText("Place Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 235, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        PharmacyOrder pharmacyOrder = new PharmacyOrder(userProcessContainer, patient, prescription, network);
        userProcessContainer.add("pharmacyOrder", pharmacyOrder);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void complainJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a drug");
            return;
        }
        String feedBack = jTextField1.getText();
        PrescriptionItem prescriptionItem = (PrescriptionItem) jTable1.getValueAt(selectedRow, 0);
        prescriptionItem.getMedicine().setFeedback(new Feedback(feedBack, patient));
        JOptionPane.showMessageDialog(null, "Feedback has been posted");
    }//GEN-LAST:event_complainJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton complainJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
