/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyWorkArea;

import Business.Enterprise.Enterprise;
import Business.Medicine.MedicineInventroy;
import Business.Network.Network;
import Business.Pharmacy.Pharmacy;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vyaas
 */
public class Inventory extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    Network network;
    Enterprise enterprise;
    /**
     * Creates new form Inventory
     */
    public Inventory(JPanel userProcessContainer, UserAccount account, Network network, Enterprise enterprise) {
        initComponents();
        this.network=network;
        this.account=account;
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        populateTable();
    }
        private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Pharmacy pharmacy= (Pharmacy)account.getCompany();
        model.setRowCount(0);
        for (MedicineInventroy mi : pharmacy.getMedicines().getMedicinesList()){
                Object[] row = new Object[3];
                row[0] = mi.getMedicine().getDrugName();
                row[1] = mi.getDrugCompany();
                row[2] = mi.getQuantity();
                model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        placeOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Drug Company", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 375, 100));

        jButton1.setText("<< back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 164, -1, -1));

        placeOrder.setText("Place Order");
        placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderActionPerformed(evt);
            }
        });
        add(placeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 164, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Inventory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderActionPerformed
        // TODO add your handling code here:
         PlaceOrder placeOrder = 
                new PlaceOrder(userProcessContainer, account, network, enterprise);
        userProcessContainer.add("PlaceOrder", placeOrder);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_placeOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton placeOrder;
    // End of variables declaration//GEN-END:variables
}
