/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyWorkArea;

import UserInterface.DoctorWorkArea.*;
import Business.Drug.DrugCompany;
import Business.Ecosystem;
import Business.Enterprise.DrugCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Medicine.MedicineInventroy;
import Business.Medicine.MedicinesInventroy;
import Business.Network.Network;
import Business.Organization.DrugAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientAdminOrganization;
import Business.Patient.Patient;
import Business.Patient.Prescription;
import Business.Patient.PrescriptionItem;
import Business.Pharmacy.Pharmacy;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicineInventoryWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author krithika
 */
public class PlaceOrder extends javax.swing.JPanel {

    /**
     * Creates new form Prescribe
     */JPanel userProcessContainer;
    Enterprise enterprise;
    Network network;
    UserAccount account;
   
    public PlaceOrder(JPanel userProcessContainer, UserAccount account, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network = network;
        this.account=account;
        this.network = network;
        this.enterprise=enterprise;
        popOrganizationComboBox();
    }

    public void popOrganizationComboBox() {
        drugCompany.removeAllItems();
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (ent instanceof DrugCompanyEnterprise) {
                DrugCompanyEnterprise dce = (DrugCompanyEnterprise) ent;
                for (DrugCompany dc : dce.getDrugDirectory().getDrugDirectory()) {
                    drugCompany.addItem(dc);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        order = new javax.swing.JButton();
        back = new javax.swing.JButton();
        drugCompany = new javax.swing.JComboBox();
        drug = new javax.swing.JComboBox();
        quantity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Drug Company");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setText("Drug");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 89, -1, -1));

        jLabel3.setText("Quantity");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 142, -1, -1));

        order.setText("Order");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 228, -1, -1));

        back.setText("<<Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 228, -1, -1));

        drugCompany.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugCompanyActionPerformed(evt);
            }
        });
        add(drugCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 29, -1, -1));

        drug.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugActionPerformed(evt);
            }
        });
        add(drug, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 78, -1, -1));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 136, 96, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
        DrugCompany dce = (DrugCompany) drugCompany.getSelectedItem();
        Medicine medicine = (Medicine) drug.getSelectedItem();
        int quantityVal = Integer.parseInt(quantity.getText());
        Pharmacy pharmacy= (Pharmacy)account.getCompany();
        MedicineInventroy mi = new MedicineInventroy(dce, medicine, quantityVal);
        MedicineInventoryWorkRequest miwr = new MedicineInventoryWorkRequest();
        miwr.setPerson(account.getPerson());
        miwr.setSender(account);
        miwr.setCompanyReceiver(dce);
        miwr.setStatus("Requested");
        miwr.setMedicinesInventroy(mi);
        enterprise.getWorkQueue().getWorkRequestList().add(miwr);
        JOptionPane.showMessageDialog(null, "Drug requested");
    }//GEN-LAST:event_orderActionPerformed

    private void drugCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugCompanyActionPerformed
        // TODO add your handling code here:
        try {
            DrugCompany dc = (DrugCompany) drugCompany.getSelectedItem();
            drug.removeAllItems();
            for (Medicine medicine : dc.getMedicines().getMedicinesList()) {
                drug.addItem(medicine);
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_drugCompanyActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void drugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);     // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox drug;
    private javax.swing.JComboBox drugCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton order;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
