/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyWorkArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Message.Message;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Patient.Prescription;
import Business.Patient.PrescriptionItem;
import Business.Pharmacy.Pharmacy;
import Business.Pharmacy.PharmacyDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PrescriptionWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.PatientWorkArea.PrescriptionJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krithika
 */
public class ViewRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRequestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private PharmacyDirectory pharmacyDirectory;
    UserAccount account;
    Organization organization;
    Network network;
    
    public ViewRequestJPanel(JPanel userProcessContainer, UserAccount account,
            Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization = organization;
        this.enterprise=enterprise;
        this.network=network;
        populateTable();
        Message message = Message.getInstance();
        jTextField1.setText(message.getMessage());
    }
   private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
            PrescriptionWorkRequest pwr = (PrescriptionWorkRequest) wr;
                Object[] row = new Object[2];
                row[0] = pwr.getPrescription();
                row[1] = pwr.getPerson().getFirstName();
                model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewPrescription = new javax.swing.JButton();
        PatientNotFOund = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        viewInventory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Doctor Name", "PatientName"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, 375, 79));

        viewPrescription.setText("View Prescription");
        viewPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPrescriptionActionPerformed(evt);
            }
        });
        add(viewPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 178, -1, -1));
        add(PatientNotFOund, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 4, 180, 20));

        jLabel6.setText("Message");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 239, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 219, 150, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Pharmacy Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 31, -1, -1));

        viewInventory.setText("View Inventory");
        viewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryActionPerformed(evt);
            }
        });
        add(viewInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 178, 141, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/pills.JPG"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 560, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void viewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryActionPerformed
        // TODO add your handling code here:
        Inventory inventory = 
                new Inventory(userProcessContainer, account, network, enterprise);
        userProcessContainer.add("ViewPrescription", inventory);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewInventoryActionPerformed

    private void viewPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPrescriptionActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Prescription prescription = (Prescription) jTable1.getValueAt(selectedRow, 0);
        ViewPrescriptionJPanel viewPrescriptionJPanel = 
                new ViewPrescriptionJPanel(userProcessContainer, prescription, account);
        userProcessContainer.add("ViewPrescription", viewPrescriptionJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPrescriptionActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PatientNotFOund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton viewInventory;
    private javax.swing.JButton viewPrescription;
    // End of variables declaration//GEN-END:variables
}
